<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void{
        $datas = [
            ["name" => "Afghanistan", "code" => "AF", "phone" => 93, "symbol" => "؋", "capital" => "Kabul", "currency" => "AFN", "continent_code" => "AS", "name_tr" => "Afganistan"],
            ["name" => "Aland Islands", "code" => "AX", "phone" => 358, "symbol" => "€", "capital" => "Mariehamn", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Aland adaları"],
            ["name" => "Albania", "code" => "AL", "phone" => 355, "symbol" => "Lek", "capital" => "Tirana", "currency" => "ALL", "continent_code" => "EU", "name_tr" => "Arnavutluk"],
            ["name" => "Algeria", "code" => "DZ", "phone" => 213, "symbol" => "دج", "capital" => "Algiers", "currency" => "DZD", "continent_code" => "AF", "name_tr" => "Cezayir"],
            ["name" => "American Samoa", "code" => "AS", "phone" => 1684, "symbol" => "$", "capital" => "Pago Pago", "currency" => "USD", "continent_code" => "OC", "name_tr" => "Amerikan Samoası"],
            ["name" => "Andorra", "code" => "AD", "phone" => 376, "symbol" => "€", "capital" => "Andorra la Vella", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Andorra"],
            ["name" => "Angola", "code" => "AO", "phone" => 244, "symbol" => "Kz", "capital" => "Luanda", "currency" => "AOA", "continent_code" => "AF", "name_tr" => "Angola"],
            ["name" => "Anguilla", "code" => "AI", "phone" => 1264, "symbol" => "$", "capital" => "The Valley", "currency" => "XCD", "continent_code" => "NA", "name_tr" => "Anguilla"],
            ["name" => "Antarctica", "code" => "AQ", "phone" => 672, "symbol" => "$", "capital" => "Antarctica", "currency" => "AAD", "continent_code" => "AN", "name_tr" => "Antarktika"],
            ["name" => "Antigua and Barbuda", "code" => "AG", "phone" => 1268, "symbol" => "$", "capital" => "St. John's", "currency" => "XCD", "continent_code" => "NA", "name_tr" => "Antigua ve Barbuda"],
            ["name" => "Argentina", "code" => "AR", "phone" => 54, "symbol" => "$", "capital" => "Buenos Aires", "currency" => "ARS", "continent_code" => "SA", "name_tr" => "Arjantin"],
            ["name" => "Armenia", "code" => "AM", "phone" => 374, "symbol" => "֏", "capital" => "Yerevan", "currency" => "AMD", "continent_code" => "AS", "name_tr" => "Ermenistan"],
            ["name" => "Aruba", "code" => "AW", "phone" => 297, "symbol" => "ƒ", "capital" => "Oranjestad", "currency" => "AWG", "continent_code" => "NA", "name_tr" => "Aruba"],
            ["name" => "Australia", "code" => "AU", "phone" => 61, "symbol" => "$", "capital" => "Canberra", "currency" => "AUD", "continent_code" => "OC", "name_tr" => "Avustralya"],
            ["name" => "Austria", "code" => "AT", "phone" => 43, "symbol" => "€", "capital" => "Vienna", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Avusturya"],
            ["name" => "Azerbaijan", "code" => "AZ", "phone" => 994, "symbol" => "m", "capital" => "Baku", "currency" => "AZN", "continent_code" => "AS", "name_tr" => "Azerbaycan"],
            ["name" => "Bahamas", "code" => "BS", "phone" => 1242, "symbol" => "B$", "capital" => "Nassau", "currency" => "BSD", "continent_code" => "NA", "name_tr" => "Bahamalar"],
            ["name" => "Bahrain", "code" => "BH", "phone" => 973, "symbol" => ".د.ب", "capital" => "Manama", "currency" => "BHD", "continent_code" => "AS", "name_tr" => "Bahreyn"],
            ["name" => "Bangladesh", "code" => "BD", "phone" => 880, "symbol" => "৳", "capital" => "Dhaka", "currency" => "BDT", "continent_code" => "AS", "name_tr" => "Bangladeş"],
            ["name" => "Barbados", "code" => "BB", "phone" => 1246, "symbol" => "Bds$", "capital" => "Bridgetown", "currency" => "BBD", "continent_code" => "NA", "name_tr" => "Barbados"],
            ["name" => "Belarus", "code" => "BY", "phone" => 375, "symbol" => "Br", "capital" => "Minsk", "currency" => "BYN", "continent_code" => "EU", "name_tr" => "Belarus"],
            ["name" => "Belgium", "code" => "BE", "phone" => 32, "symbol" => "€", "capital" => "Brussels", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Belçika"],
            ["name" => "Belize", "code" => "BZ", "phone" => 501, "symbol" => "$", "capital" => "Belmopan", "currency" => "BZD", "continent_code" => "NA", "name_tr" => "Belize"],
            ["name" => "Benin", "code" => "BJ", "phone" => 229, "symbol" => "CFA", "capital" => "Porto-Novo", "currency" => "XOF", "continent_code" => "AF", "name_tr" => "Benin"],
            ["name" => "Bermuda", "code" => "BM", "phone" => 1441, "symbol" => "$", "capital" => "Hamilton", "currency" => "BMD", "continent_code" => "NA", "name_tr" => "Bermuda"],
            ["name" => "Bhutan", "code" => "BT", "phone" => 975, "symbol" => "Nu.", "capital" => "Thimphu", "currency" => "BTN", "continent_code" => "AS", "name_tr" => "Butan"],
            ["name" => "Bolivia", "code" => "BO", "phone" => 591, "symbol" => "Bs.", "capital" => "Sucre", "currency" => "BOB", "continent_code" => "SA", "name_tr" => "Bolivya"],
            ["name" => "Bonaire, Sint Eustatius and Saba", "code" => "BQ", "phone" => 599, "symbol" => "$", "capital" => "Kralendijk", "currency" => "USD", "continent_code" => "NA", "name_tr" => "Bonaire, Sint Eustatius ve Saba"],
            ["name" => "Bosnia and Herzegovina", "code" => "BA", "phone" => 387, "symbol" => "KM", "capital" => "Sarajevo", "currency" => "BAM", "continent_code" => "EU", "name_tr" => "Bosna Hersek"],
            ["name" => "Botswana", "code" => "BW", "phone" => 267, "symbol" => "P", "capital" => "Gaborone", "currency" => "BWP", "continent_code" => "AF", "name_tr" => "Botsvana"],
            ["name" => "Bouvet Island", "code" => "BV", "phone" => 55, "symbol" => "kr", "capital" => "", "currency" => "NOK", "continent_code" => "AN", "name_tr" => "Bouvet Adası"],
            ["name" => "Brazil", "code" => "BR", "phone" => 55, "symbol" => "R$", "capital" => "Brasilia", "currency" => "BRL", "continent_code" => "SA", "name_tr" => "Brezilya"],
            ["name" => "British Indian Ocean Territory", "code" => "IO", "phone" => 246, "symbol" => "$", "capital" => "Diego Garcia", "currency" => "USD", "continent_code" => "AS", "name_tr" => "İngiliz Hint Okyanusu Bölgesi"],
            ["name" => "Brunei Darussalam", "code" => "BN", "phone" => 673, "symbol" => "B$", "capital" => "Bandar Seri Begawan", "currency" => "BND", "continent_code" => "AS", "name_tr" => "Brunei Darussalam"],
            ["name" => "Bulgaria", "code" => "BG", "phone" => 359, "symbol" => "Лв.", "capital" => "Sofia", "currency" => "BGN", "continent_code" => "EU", "name_tr" => "Bulgaristan"],
            ["name" => "Burkina Faso", "code" => "BF", "phone" => 226, "symbol" => "CFA", "capital" => "Ouagadougou", "currency" => "XOF", "continent_code" => "AF", "name_tr" => "Burkina Faso"],
            ["name" => "Burundi", "code" => "BI", "phone" => 257, "symbol" => "FBu", "capital" => "Bujumbura", "currency" => "BIF", "continent_code" => "AF", "name_tr" => "Burundi"],
            ["name" => "Cambodia", "code" => "KH", "phone" => 855, "symbol" => "KHR", "capital" => "Phnom Penh", "currency" => "KHR", "continent_code" => "AS", "name_tr" => "Kamboçya"],
            ["name" => "Cameroon", "code" => "CM", "phone" => 237, "symbol" => "FCFA", "capital" => "Yaounde", "currency" => "XAF", "continent_code" => "AF", "name_tr" => "Kamerun"],
            ["name" => "Canada", "code" => "CA", "phone" => 1, "symbol" => "$", "capital" => "Ottawa", "currency" => "CAD", "continent_code" => "NA", "name_tr" => "Kanada"],
            ["name" => "Cape Verde", "code" => "CV", "phone" => 238, "symbol" => "$", "capital" => "Praia", "currency" => "CVE", "continent_code" => "AF", "name_tr" => "Cape Verde"],
            ["name" => "Cayman Islands", "code" => "KY", "phone" => 1345, "symbol" => "$", "capital" => "George Town", "currency" => "KYD", "continent_code" => "NA", "name_tr" => "Cayman Adaları"],
            ["name" => "Central African Republic", "code" => "CF", "phone" => 236, "symbol" => "FCFA", "capital" => "Bangui", "currency" => "XAF", "continent_code" => "AF", "name_tr" => "Orta Afrika Cumhuriyeti"],
            ["name" => "Chad", "code" => "TD", "phone" => 235, "symbol" => "FCFA", "capital" => "N'Djamena", "currency" => "XAF", "continent_code" => "AF", "name_tr" => "Çad"],
            ["name" => "Chile", "code" => "CL", "phone" => 56, "symbol" => "$", "capital" => "Santiago", "currency" => "CLP", "continent_code" => "SA", "name_tr" => "Şili"],
            ["name" => "China", "code" => "CN", "phone" => 86, "symbol" => "¥", "capital" => "Beijing", "currency" => "CNY", "continent_code" => "AS", "name_tr" => "Çin"],
            ["name" => "Christmas Island", "code" => "CX", "phone" => 61, "symbol" => "$", "capital" => "Flying Fish Cove", "currency" => "AUD", "continent_code" => "AS", "name_tr" => "Noel Adası"],
            ["name" => "Cocos (Keeling) Islands", "code" => "CC", "phone" => 672, "symbol" => "$", "capital" => "West Island", "currency" => "AUD", "continent_code" => "AS", "name_tr" => "Cocos (Keeling) Adaları"],
            ["name" => "Colombia", "code" => "CO", "phone" => 57, "symbol" => "$", "capital" => "Bogota", "currency" => "COP", "continent_code" => "SA", "name_tr" => "Kolombiya"],
            ["name" => "Comoros", "code" => "KM", "phone" => 269, "symbol" => "CF", "capital" => "Moroni", "currency" => "KMF", "continent_code" => "AF", "name_tr" => "Komorlar"],
            ["name" => "Congo", "code" => "CG", "phone" => 242, "symbol" => "FC", "capital" => "Brazzaville", "currency" => "XAF", "continent_code" => "AF", "name_tr" => "Kongo"],
            ["name" => "Congo, Democratic Republic of the Congo", "code" => "CD", "phone" => 242, "symbol" => "FC", "capital" => "Kinshasa", "currency" => "CDF", "continent_code" => "AF", "name_tr" => "Kongo, Demokratik Kongo Cumhuriyeti"],
            ["name" => "Cook Islands", "code" => "CK", "phone" => 682, "symbol" => "$", "capital" => "Avarua", "currency" => "NZD", "continent_code" => "OC", "name_tr" => "Cook Adaları"],
            ["name" => "Costa Rica", "code" => "CR", "phone" => 506, "symbol" => "₡", "capital" => "San Jose", "currency" => "CRC", "continent_code" => "NA", "name_tr" => "Kosta Rika"],
            ["name" => "Cote D'Ivoire", "code" => "CI", "phone" => 225, "symbol" => "CFA", "capital" => "Yamoussoukro", "currency" => "XOF", "continent_code" => "AF", "name_tr" => "Fildişi Sahili"],
            ["name" => "Croatia", "code" => "HR", "phone" => 385, "symbol" => "kn", "capital" => "Zagreb", "currency" => "HRK", "continent_code" => "EU", "name_tr" => "Hırvatistan"],
            ["name" => "Cuba", "code" => "CU", "phone" => 53, "symbol" => "$", "capital" => "Havana", "currency" => "CUP", "continent_code" => "NA", "name_tr" => "Küba"],
            ["name" => "Curacao", "code" => "CW", "phone" => 599, "symbol" => "ƒ", "capital" => "Willemstad", "currency" => "ANG", "continent_code" => "NA", "name_tr" => "Curacao"],
            ["name" => "Cyprus", "code" => "CY", "phone" => 357, "symbol" => "€", "capital" => "Nicosia", "currency" => "EUR", "continent_code" => "AS", "name_tr" => "Kıbrıs"],
            ["name" => "Czech Republic", "code" => "CZ", "phone" => 420, "symbol" => "Kč", "capital" => "Prague", "currency" => "CZK", "continent_code" => "EU", "name_tr" => "Çek Cumhuriyeti"],
            ["name" => "Denmark", "code" => "DK", "phone" => 45, "symbol" => "Kr.", "capital" => "Copenhagen", "currency" => "DKK", "continent_code" => "EU", "name_tr" => "Danimarka"],
            ["name" => "Djibouti", "code" => "DJ", "phone" => 253, "symbol" => "Fdj", "capital" => "Djibouti", "currency" => "DJF", "continent_code" => "AF", "name_tr" => "Cibuti"],
            ["name" => "Dominica", "code" => "DM", "phone" => 1767, "symbol" => "$", "capital" => "Roseau", "currency" => "XCD", "continent_code" => "NA", "name_tr" => "Dominika"],
            ["name" => "Dominican Republic", "code" => "DO", "phone" => 1809, "symbol" => "$", "capital" => "Santo Domingo", "currency" => "DOP", "continent_code" => "NA", "name_tr" => "Dominik Cumhuriyeti"],
            ["name" => "Ecuador", "code" => "EC", "phone" => 593, "symbol" => "$", "capital" => "Quito", "currency" => "USD", "continent_code" => "SA", "name_tr" => "Ekvador"],
            ["name" => "Egypt", "code" => "EG", "phone" => 20, "symbol" => "ج.م", "capital" => "Cairo", "currency" => "EGP", "continent_code" => "AF", "name_tr" => "Mısır"],
            ["name" => "El Salvador", "code" => "SV", "phone" => 503, "symbol" => "$", "capital" => "San Salvador", "currency" => "USD", "continent_code" => "NA", "name_tr" => "El Salvador"],
            ["name" => "Equatorial Guinea", "code" => "GQ", "phone" => 240, "symbol" => "FCFA", "capital" => "Malabo", "currency" => "XAF", "continent_code" => "AF", "name_tr" => "Ekvator Ginesi"],
            ["name" => "Eritrea", "code" => "ER", "phone" => 291, "symbol" => "Nfk", "capital" => "Asmara", "currency" => "ERN", "continent_code" => "AF", "name_tr" => "Eritre"],
            ["name" => "Estonia", "code" => "EE", "phone" => 372, "symbol" => "€", "capital" => "Tallinn", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Estonya"],
            ["name" => "Ethiopia", "code" => "ET", "phone" => 251, "symbol" => "Nkf", "capital" => "Addis Ababa", "currency" => "ETB", "continent_code" => "AF", "name_tr" => "Etiyopya"],
            ["name" => "Falkland Islands (Malvinas)", "code" => "FK", "phone" => 500, "symbol" => "£", "capital" => "Stanley", "currency" => "FKP", "continent_code" => "SA", "name_tr" => "Falkland Adaları (Malvinas)"],
            ["name" => "Faroe Islands", "code" => "FO", "phone" => 298, "symbol" => "Kr.", "capital" => "Torshavn", "currency" => "DKK", "continent_code" => "EU", "name_tr" => "Faroe Adaları"],
            ["name" => "Fiji", "code" => "FJ", "phone" => 679, "symbol" => "FJ$", "capital" => "Suva", "currency" => "FJD", "continent_code" => "OC", "name_tr" => "Fiji"],
            ["name" => "Finland", "code" => "FI", "phone" => 358, "symbol" => "€", "capital" => "Helsinki", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Finlandiya"],
            ["name" => "France", "code" => "FR", "phone" => 33, "symbol" => "€", "capital" => "Paris", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Fransa"],
            ["name" => "French Guiana", "code" => "GF", "phone" => 594, "symbol" => "€", "capital" => "Cayenne", "currency" => "EUR", "continent_code" => "SA", "name_tr" => "Fransız Guyanası"],
            ["name" => "French Polynesia", "code" => "PF", "phone" => 689, "symbol" => "₣", "capital" => "Papeete", "currency" => "XPF", "continent_code" => "OC", "name_tr" => "Fransız Polinezyası"],
            ["name" => "French Southern Territories", "code" => "TF", "phone" => 262, "symbol" => "€", "capital" => "Port-aux-Francais", "currency" => "EUR", "continent_code" => "AN", "name_tr" => "Fransız Güney Toprakları"],
            ["name" => "Gabon", "code" => "GA", "phone" => 241, "symbol" => "FCFA", "capital" => "Libreville", "currency" => "XAF", "continent_code" => "AF", "name_tr" => "Gabon"],
            ["name" => "Gambia", "code" => "GM", "phone" => 220, "symbol" => "D", "capital" => "Banjul", "currency" => "GMD", "continent_code" => "AF", "name_tr" => "Gambiya"],
            ["name" => "Georgia", "code" => "GE", "phone" => 995, "symbol" => "ლ", "capital" => "Tbilisi", "currency" => "GEL", "continent_code" => "AS", "name_tr" => "Gürcistan"],
            ["name" => "Germany", "code" => "DE", "phone" => 49, "symbol" => "€", "capital" => "Berlin", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Almanya"],
            ["name" => "Ghana", "code" => "GH", "phone" => 233, "symbol" => "GH₵", "capital" => "Accra", "currency" => "GHS", "continent_code" => "AF", "name_tr" => "Gana"],
            ["name" => "Gibraltar", "code" => "GI", "phone" => 350, "symbol" => "£", "capital" => "Gibraltar", "currency" => "GIP", "continent_code" => "EU", "name_tr" => "Cebelitarık"],
            ["name" => "Greece", "code" => "GR", "phone" => 30, "symbol" => "€", "capital" => "Athens", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Yunanistan"],
            ["name" => "Greenland", "code" => "GL", "phone" => 299, "symbol" => "Kr.", "capital" => "Nuuk", "currency" => "DKK", "continent_code" => "NA", "name_tr" => "Grönland"],
            ["name" => "Grenada", "code" => "GD", "phone" => 1473, "symbol" => "$", "capital" => "St. George's", "currency" => "XCD", "continent_code" => "NA", "name_tr" => "Grenada"],
            ["name" => "Guadeloupe", "code" => "GP", "phone" => 590, "symbol" => "€", "capital" => "Basse-Terre", "currency" => "EUR", "continent_code" => "NA", "name_tr" => "Guadeloupe"],
            ["name" => "Guam", "code" => "GU", "phone" => 1671, "symbol" => "$", "capital" => "Hagatna", "currency" => "USD", "continent_code" => "OC", "name_tr" => "Guam"],
            ["name" => "Guatemala", "code" => "GT", "phone" => 502, "symbol" => "Q", "capital" => "Guatemala City", "currency" => "GTQ", "continent_code" => "NA", "name_tr" => "Guatemala"],
            ["name" => "Guernsey", "code" => "GG", "phone" => 44, "symbol" => "£", "capital" => "St Peter Port", "currency" => "GBP", "continent_code" => "EU", "name_tr" => "Guernsey"],
            ["name" => "Guinea", "code" => "GN", "phone" => 224, "symbol" => "FG", "capital" => "Conakry", "currency" => "GNF", "continent_code" => "AF", "name_tr" => "Gine"],
            ["name" => "Guinea-Bissau", "code" => "GW", "phone" => 245, "symbol" => "CFA", "capital" => "Bissau", "currency" => "XOF", "continent_code" => "AF", "name_tr" => "Gine-Bissau"],
            ["name" => "Guyana", "code" => "GY", "phone" => 592, "symbol" => "$", "capital" => "Georgetown", "currency" => "GYD", "continent_code" => "SA", "name_tr" => "Guyana"],
            ["name" => "Haiti", "code" => "HT", "phone" => 509, "symbol" => "G", "capital" => "Port-au-Prince", "currency" => "HTG", "continent_code" => "NA", "name_tr" => "Haiti"],
            ["name" => "Heard Island and McDonald Islands", "code" => "HM", "phone" => 0, "symbol" => "$", "capital" => "", "currency" => "AUD", "continent_code" => "AN", "name_tr" => "Heard Adası ve McDonald Adaları"],
            ["name" => "Holy See (Vatican City State)", "code" => "VA", "phone" => 39, "symbol" => "€", "capital" => "Vatican City", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Holy See (Vatikan Şehir Devleti)"],
            ["name" => "Honduras", "code" => "HN", "phone" => 504, "symbol" => "L", "capital" => "Tegucigalpa", "currency" => "HNL", "continent_code" => "NA", "name_tr" => "Honduras"],
            ["name" => "Hong Kong", "code" => "HK", "phone" => 852, "symbol" => "$", "capital" => "Hong Kong", "currency" => "HKD", "continent_code" => "AS", "name_tr" => "Hong Kong"],
            ["name" => "Hungary", "code" => "HU", "phone" => 36, "symbol" => "Ft", "capital" => "Budapest", "currency" => "HUF", "continent_code" => "EU", "name_tr" => "Macaristan"],
            ["name" => "Iceland", "code" => "IS", "phone" => 354, "symbol" => "kr", "capital" => "Reykjavik", "currency" => "ISK", "continent_code" => "EU", "name_tr" => "İzlanda"],
            ["name" => "India", "code" => "IN", "phone" => 91, "symbol" => "₹", "capital" => "New Delhi", "currency" => "INR", "continent_code" => "AS", "name_tr" => "Hindistan"],
            ["name" => "Indonesia", "code" => "ID", "phone" => 62, "symbol" => "Rp", "capital" => "Jakarta", "currency" => "IDR", "continent_code" => "AS", "name_tr" => "Endonezya"],
            ["name" => "Iran, Islamic Republic of", "code" => "IR", "phone" => 98, "symbol" => "﷼", "capital" => "Tehran", "currency" => "IRR", "continent_code" => "AS", "name_tr" => "İran İslam Cumhuriyeti"],
            ["name" => "Iraq", "code" => "IQ", "phone" => 964, "symbol" => "د.ع", "capital" => "Baghdad", "currency" => "IQD", "continent_code" => "AS", "name_tr" => "Irak"],
            ["name" => "Ireland", "code" => "IE", "phone" => 353, "symbol" => "€", "capital" => "Dublin", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "İrlanda"],
            ["name" => "Isle of Man", "code" => "IM", "phone" => 44, "symbol" => "£", "capital" => "Douglas, Isle of Man", "currency" => "GBP", "continent_code" => "EU", "name_tr" => "Man Adası"],
            ["name" => "Israel", "code" => "IL", "phone" => 972, "symbol" => "₪", "capital" => "Jerusalem", "currency" => "ILS", "continent_code" => "AS", "name_tr" => "İsrail"],
            ["name" => "Italy", "code" => "IT", "phone" => 39, "symbol" => "€", "capital" => "Rome", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "İtalya"],
            ["name" => "Jamaica", "code" => "JM", "phone" => 1876, "symbol" => "J$", "capital" => "Kingston", "currency" => "JMD", "continent_code" => "NA", "name_tr" => "Jamaika"],
            ["name" => "Japan", "code" => "JP", "phone" => 81, "symbol" => "¥", "capital" => "Tokyo", "currency" => "JPY", "continent_code" => "AS", "name_tr" => "Japonya"],
            ["name" => "Jersey", "code" => "JE", "phone" => 44, "symbol" => "£", "capital" => "Saint Helier", "currency" => "GBP", "continent_code" => "EU", "name_tr" => "Jersey"],
            ["name" => "Jordan", "code" => "JO", "phone" => 962, "symbol" => "ا.د", "capital" => "Amman", "currency" => "JOD", "continent_code" => "AS", "name_tr" => "Ürdün"],
            ["name" => "Kazakhstan", "code" => "KZ", "phone" => 7, "symbol" => "лв", "capital" => "Astana", "currency" => "KZT", "continent_code" => "AS", "name_tr" => "Kazakistan"],
            ["name" => "Kenya", "code" => "KE", "phone" => 254, "symbol" => "KSh", "capital" => "Nairobi", "currency" => "KES", "continent_code" => "AF", "name_tr" => "Kenya"],
            ["name" => "Kiribati", "code" => "KI", "phone" => 686, "symbol" => "$", "capital" => "Tarawa", "currency" => "AUD", "continent_code" => "OC", "name_tr" => "Kiribati"],
            ["name" => "Korea, Democratic People's Republic of", "code" => "KP", "phone" => 850, "symbol" => "₩", "capital" => "Pyongyang", "currency" => "KPW", "continent_code" => "AS", "name_tr" => "Kore Demokratik Halk Cumhuriyeti"],
            ["name" => "Korea, Republic of", "code" => "KR", "phone" => 82, "symbol" => "₩", "capital" => "Seoul", "currency" => "KRW", "continent_code" => "AS", "name_tr" => "Kore Cumhuriyeti"],
            ["name" => "Kosovo", "code" => "XK", "phone" => 383, "symbol" => "€", "capital" => "Pristina", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Kosova"],
            ["name" => "Kuwait", "code" => "KW", "phone" => 965, "symbol" => "ك.د", "capital" => "Kuwait City", "currency" => "KWD", "continent_code" => "AS", "name_tr" => "Kuveyt"],
            ["name" => "Kyrgyzstan", "code" => "KG", "phone" => 996, "symbol" => "лв", "capital" => "Bishkek", "currency" => "KGS", "continent_code" => "AS", "name_tr" => "Kırgızistan"],
            ["name" => "Lao People's Democratic Republic", "code" => "LA", "phone" => 856, "symbol" => "₭", "capital" => "Vientiane", "currency" => "LAK", "continent_code" => "AS", "name_tr" => "Lao Demokratik Halk Cumhuriyeti"],
            ["name" => "Latvia", "code" => "LV", "phone" => 371, "symbol" => "€", "capital" => "Riga", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Letonya"],
            ["name" => "Lebanon", "code" => "LB", "phone" => 961, "symbol" => "£", "capital" => "Beirut", "currency" => "LBP", "continent_code" => "AS", "name_tr" => "Lübnan"],
            ["name" => "Lesotho", "code" => "LS", "phone" => 266, "symbol" => "L", "capital" => "Maseru", "currency" => "LSL", "continent_code" => "AF", "name_tr" => "Lesoto"],
            ["name" => "Liberia", "code" => "LR", "phone" => 231, "symbol" => "$", "capital" => "Monrovia", "currency" => "LRD", "continent_code" => "AF", "name_tr" => "Liberya"],
            ["name" => "Libyan Arab Jamahiriya", "code" => "LY", "phone" => 218, "symbol" => "د.ل", "capital" => "Tripolis", "currency" => "LYD", "continent_code" => "AF", "name_tr" => "Libya Arap Cemahiriyası"],
            ["name" => "Liechtenstein", "code" => "LI", "phone" => 423, "symbol" => "CHf", "capital" => "Vaduz", "currency" => "CHF", "continent_code" => "EU", "name_tr" => "Lihtenştayn"],
            ["name" => "Lithuania", "code" => "LT", "phone" => 370, "symbol" => "€", "capital" => "Vilnius", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Litvanya"],
            ["name" => "Luxembourg", "code" => "LU", "phone" => 352, "symbol" => "€", "capital" => "Luxembourg", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Lüksemburg"],
            ["name" => "Macao", "code" => "MO", "phone" => 853, "symbol" => "$", "capital" => "Macao", "currency" => "MOP", "continent_code" => "AS", "name_tr" => "Makao"],
            ["name" => "Macedonia, the Former Yugoslav Republic of", "code" => "MK", "phone" => 389, "symbol" => "ден", "capital" => "Skopje", "currency" => "MKD", "continent_code" => "EU", "name_tr" => "Makedonya Eski Yugoslav Cumhuriyeti"],
            ["name" => "Madagascar", "code" => "MG", "phone" => 261, "symbol" => "Ar", "capital" => "Antananarivo", "currency" => "MGA", "continent_code" => "AF", "name_tr" => "Madagaskar"],
            ["name" => "Malawi", "code" => "MW", "phone" => 265, "symbol" => "MK", "capital" => "Lilongwe", "currency" => "MWK", "continent_code" => "AF", "name_tr" => "Malawi"],
            ["name" => "Malaysia", "code" => "MY", "phone" => 60, "symbol" => "RM", "capital" => "Kuala Lumpur", "currency" => "MYR", "continent_code" => "AS", "name_tr" => "Malezya"],
            ["name" => "Maldives", "code" => "MV", "phone" => 960, "symbol" => "Rf", "capital" => "Male", "currency" => "MVR", "continent_code" => "AS", "name_tr" => "Maldivler"],
            ["name" => "Mali", "code" => "ML", "phone" => 223, "symbol" => "CFA", "capital" => "Bamako", "currency" => "XOF", "continent_code" => "AF", "name_tr" => "Mali"],
            ["name" => "Malta", "code" => "MT", "phone" => 356, "symbol" => "€", "capital" => "Valletta", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Malta"],
            ["name" => "Marshall Islands", "code" => "MH", "phone" => 692, "symbol" => "$", "capital" => "Majuro", "currency" => "USD", "continent_code" => "OC", "name_tr" => "Marşal Adaları"],
            ["name" => "Martinique", "code" => "MQ", "phone" => 596, "symbol" => "€", "capital" => "Fort-de-France", "currency" => "EUR", "continent_code" => "NA", "name_tr" => "Martinik"],
            ["name" => "Mauritania", "code" => "MR", "phone" => 222, "symbol" => "MRU", "capital" => "Nouakchott", "currency" => "MRO", "continent_code" => "AF", "name_tr" => "Moritanya"],
            ["name" => "Mauritius", "code" => "MU", "phone" => 230, "symbol" => "₨", "capital" => "Port Louis", "currency" => "MUR", "continent_code" => "AF", "name_tr" => "Mauritius"],
            ["name" => "Mayotte", "code" => "YT", "phone" => 262, "symbol" => "€", "capital" => "Mamoudzou", "currency" => "EUR", "continent_code" => "AF", "name_tr" => "Mayotte"],
            ["name" => "Mexico", "code" => "MX", "phone" => 52, "symbol" => "$", "capital" => "Mexico City", "currency" => "MXN", "continent_code" => "NA", "name_tr" => "Meksika"],
            ["name" => "Micronesia, Federated States of", "code" => "FM", "phone" => 691, "symbol" => "$", "capital" => "Palikir", "currency" => "USD", "continent_code" => "OC", "name_tr" => "Mikronezya Federal Devletleri"],
            ["name" => "Moldova, Republic of", "code" => "MD", "phone" => 373, "symbol" => "L", "capital" => "Chisinau", "currency" => "MDL", "continent_code" => "EU", "name_tr" => "Moldova Cumhuriyeti"],
            ["name" => "Monaco", "code" => "MC", "phone" => 377, "symbol" => "€", "capital" => "Monaco", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Monako"],
            ["name" => "Mongolia", "code" => "MN", "phone" => 976, "symbol" => "₮", "capital" => "Ulan Bator", "currency" => "MNT", "continent_code" => "AS", "name_tr" => "Moğolistan"],
            ["name" => "Montenegro", "code" => "ME", "phone" => 382, "symbol" => "€", "capital" => "Podgorica", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Karadağ"],
            ["name" => "Montserrat", "code" => "MS", "phone" => 1664, "symbol" => "$", "capital" => "Plymouth", "currency" => "XCD", "continent_code" => "NA", "name_tr" => "Montserrat"],
            ["name" => "Morocco", "code" => "MA", "phone" => 212, "symbol" => "DH", "capital" => "Rabat", "currency" => "MAD", "continent_code" => "AF", "name_tr" => "Fas"],
            ["name" => "Mozambique", "code" => "MZ", "phone" => 258, "symbol" => "MT", "capital" => "Maputo", "currency" => "MZN", "continent_code" => "AF", "name_tr" => "Mozambik"],
            ["name" => "Myanmar", "code" => "MM", "phone" => 95, "symbol" => "K", "capital" => "Nay Pyi Taw", "currency" => "MMK", "continent_code" => "AS", "name_tr" => "Myanmar"],
            ["name" => "Namibia", "code" => "NA", "phone" => 264, "symbol" => "$", "capital" => "Windhoek", "currency" => "NAD", "continent_code" => "AF", "name_tr" => "Namibya"],
            ["name" => "Nauru", "code" => "NR", "phone" => 674, "symbol" => "$", "capital" => "Yaren", "currency" => "AUD", "continent_code" => "OC", "name_tr" => "Nauru"],
            ["name" => "Nepal", "code" => "NP", "phone" => 977, "symbol" => "₨", "capital" => "Kathmandu", "currency" => "NPR", "continent_code" => "AS", "name_tr" => "Nepal"],
            ["name" => "Netherlands", "code" => "NL", "phone" => 31, "symbol" => "€", "capital" => "Amsterdam", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Hollanda"],
            ["name" => "Netherlands Antilles", "code" => "AN", "phone" => 599, "symbol" => "NAf", "capital" => "Willemstad", "currency" => "ANG", "continent_code" => "NA", "name_tr" => "Hollanda Antilleri"],
            ["name" => "New Caledonia", "code" => "NC", "phone" => 687, "symbol" => "₣", "capital" => "Noumea", "currency" => "XPF", "continent_code" => "OC", "name_tr" => "Yeni Kaledonya"],
            ["name" => "New Zealand", "code" => "NZ", "phone" => 64, "symbol" => "$", "capital" => "Wellington", "currency" => "NZD", "continent_code" => "OC", "name_tr" => "Yeni Zelanda"],
            ["name" => "Nicaragua", "code" => "NI", "phone" => 505, "symbol" => "C$", "capital" => "Managua", "currency" => "NIO", "continent_code" => "NA", "name_tr" => "Nikaragua"],
            ["name" => "Niger", "code" => "NE", "phone" => 227, "symbol" => "CFA", "capital" => "Niamey", "currency" => "XOF", "continent_code" => "AF", "name_tr" => "Nijer"],
            ["name" => "Nigeria", "code" => "NG", "phone" => 234, "symbol" => "₦", "capital" => "Abuja", "currency" => "NGN", "continent_code" => "AF", "name_tr" => "Nijerya"],
            ["name" => "Niue", "code" => "NU", "phone" => 683, "symbol" => "$", "capital" => "Alofi", "currency" => "NZD", "continent_code" => "OC", "name_tr" => "Niue"],
            ["name" => "Norfolk Island", "code" => "NF", "phone" => 672, "symbol" => "$", "capital" => "Kingston", "currency" => "AUD", "continent_code" => "OC", "name_tr" => "Norfolk Adası"],
            ["name" => "Northern Mariana Islands", "code" => "MP", "phone" => 1670, "symbol" => "$", "capital" => "Saipan", "currency" => "USD", "continent_code" => "OC", "name_tr" => "Kuzey Mariana Adaları"],
            ["name" => "Norway", "code" => "NO", "phone" => 47, "symbol" => "kr", "capital" => "Oslo", "currency" => "NOK", "continent_code" => "EU", "name_tr" => "Norveç"],
            ["name" => "Oman", "code" => "OM", "phone" => 968, "symbol" => ".ع.ر", "capital" => "Muscat", "currency" => "OMR", "continent_code" => "AS", "name_tr" => "Umman"],
            ["name" => "Pakistan", "code" => "PK", "phone" => 92, "symbol" => "₨", "capital" => "Islamabad", "currency" => "PKR", "continent_code" => "AS", "name_tr" => "Pakistan"],
            ["name" => "Palau", "code" => "PW", "phone" => 680, "symbol" => "$", "capital" => "Melekeok", "currency" => "USD", "continent_code" => "OC", "name_tr" => "Palau"],
            ["name" => "Palestinian Territory, Occupied", "code" => "PS", "phone" => 970, "symbol" => "₪", "capital" => "East Jerusalem", "currency" => "ILS", "continent_code" => "AS", "name_tr" => "Filistin Arazisi, İşgal altında"],
            ["name" => "Panama", "code" => "PA", "phone" => 507, "symbol" => "B/.", "capital" => "Panama City", "currency" => "PAB", "continent_code" => "NA", "name_tr" => "Panama"],
            ["name" => "Papua New Guinea", "code" => "PG", "phone" => 675, "symbol" => "K", "capital" => "Port Moresby", "currency" => "PGK", "continent_code" => "OC", "name_tr" => "Papua Yeni Gine"],
            ["name" => "Paraguay", "code" => "PY", "phone" => 595, "symbol" => "₲", "capital" => "Asuncion", "currency" => "PYG", "continent_code" => "SA", "name_tr" => "Paraguay"],
            ["name" => "Peru", "code" => "PE", "phone" => 51, "symbol" => "S/.", "capital" => "Lima", "currency" => "PEN", "continent_code" => "SA", "name_tr" => "Peru"],
            ["name" => "Philippines", "code" => "PH", "phone" => 63, "symbol" => "₱", "capital" => "Manila", "currency" => "PHP", "continent_code" => "AS", "name_tr" => "Filipinler"],
            ["name" => "Pitcairn", "code" => "PN", "phone" => 64, "symbol" => "$", "capital" => "Adamstown", "currency" => "NZD", "continent_code" => "OC", "name_tr" => "Pitcairn"],
            ["name" => "Poland", "code" => "PL", "phone" => 48, "symbol" => "zł", "capital" => "Warsaw", "currency" => "PLN", "continent_code" => "EU", "name_tr" => "Polonya"],
            ["name" => "Portugal", "code" => "PT", "phone" => 351, "symbol" => "€", "capital" => "Lisbon", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Portekiz"],
            ["name" => "Puerto Rico", "code" => "PR", "phone" => 1787, "symbol" => "$", "capital" => "San Juan", "currency" => "USD", "continent_code" => "NA", "name_tr" => "Porto Riko"],
            ["name" => "Qatar", "code" => "QA", "phone" => 974, "symbol" => "ق.ر", "capital" => "Doha", "currency" => "QAR", "continent_code" => "AS", "name_tr" => "Katar"],
            ["name" => "Reunion", "code" => "RE", "phone" => 262, "symbol" => "€", "capital" => "Saint-Denis", "currency" => "EUR", "continent_code" => "AF", "name_tr" => "Reunion"],
            ["name" => "Romania", "code" => "RO", "phone" => 40, "symbol" => "lei", "capital" => "Bucharest", "currency" => "RON", "continent_code" => "EU", "name_tr" => "Romanya"],
            ["name" => "Russian Federation", "code" => "RU", "phone" => 7, "symbol" => "₽", "capital" => "Moscow", "currency" => "RUB", "continent_code" => "AS", "name_tr" => "Rusya Federasyonu"],
            ["name" => "Rwanda", "code" => "RW", "phone" => 250, "symbol" => "FRw", "capital" => "Kigali", "currency" => "RWF", "continent_code" => "AF", "name_tr" => "Ruanda"],
            ["name" => "Saint Barthelemy", "code" => "BL", "phone" => 590, "symbol" => "€", "capital" => "Gustavia", "currency" => "EUR", "continent_code" => "NA", "name_tr" => "Saint Barthelemy"],
            ["name" => "Saint Helena", "code" => "SH", "phone" => 290, "symbol" => "£", "capital" => "Jamestown", "currency" => "SHP", "continent_code" => "AF", "name_tr" => "Saint Helena"],
            ["name" => "Saint Kitts and Nevis", "code" => "KN", "phone" => 1869, "symbol" => "$", "capital" => "Basseterre", "currency" => "XCD", "continent_code" => "NA", "name_tr" => "Saint Kitts ve Nevis"],
            ["name" => "Saint Lucia", "code" => "LC", "phone" => 1758, "symbol" => "$", "capital" => "Castries", "currency" => "XCD", "continent_code" => "NA", "name_tr" => "Saint Lucia"],
            ["name" => "Saint Martin", "code" => "MF", "phone" => 590, "symbol" => "€", "capital" => "Marigot", "currency" => "EUR", "continent_code" => "NA", "name_tr" => "Aziz Martin"],
            ["name" => "Saint Pierre and Miquelon", "code" => "PM", "phone" => 508, "symbol" => "€", "capital" => "Saint-Pierre", "currency" => "EUR", "continent_code" => "NA", "name_tr" => "Saint Pierre ve Miquelon"],
            ["name" => "Saint Vincent and the Grenadines", "code" => "VC", "phone" => 1784, "symbol" => "$", "capital" => "Kingstown", "currency" => "XCD", "continent_code" => "NA", "name_tr" => "Saint Vincent ve Grenadinler"],
            ["name" => "Samoa", "code" => "WS", "phone" => 684, "symbol" => "SAT", "capital" => "Apia", "currency" => "WST", "continent_code" => "OC", "name_tr" => "Samoa"],
            ["name" => "San Marino", "code" => "SM", "phone" => 378, "symbol" => "€", "capital" => "San Marino", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "San Marino"],
            ["name" => "Sao Tome and Principe", "code" => "ST", "phone" => 239, "symbol" => "Db", "capital" => "Sao Tome", "currency" => "STD", "continent_code" => "AF", "name_tr" => "Sao Tome ve Principe"],
            ["name" => "Saudi Arabia", "code" => "SA", "phone" => 966, "symbol" => "﷼", "capital" => "Riyadh", "currency" => "SAR", "continent_code" => "AS", "name_tr" => "Suudi Arabistan"],
            ["name" => "Senegal", "code" => "SN", "phone" => 221, "symbol" => "CFA", "capital" => "Dakar", "currency" => "XOF", "continent_code" => "AF", "name_tr" => "Senegal"],
            ["name" => "Serbia", "code" => "RS", "phone" => 381, "symbol" => "din", "capital" => "Belgrade", "currency" => "RSD", "continent_code" => "EU", "name_tr" => "Sırbistan"],
            ["name" => "Serbia and Montenegro", "code" => "CS", "phone" => 381, "symbol" => "din", "capital" => "Belgrade", "currency" => "RSD", "continent_code" => "EU", "name_tr" => "Sırbistan ve Karadağ"],
            ["name" => "Seychelles", "code" => "SC", "phone" => 248, "symbol" => "SRe", "capital" => "Victoria", "currency" => "SCR", "continent_code" => "AF", "name_tr" => "Seyşeller"],
            ["name" => "Sierra Leone", "code" => "SL", "phone" => 232, "symbol" => "Le", "capital" => "Freetown", "currency" => "SLL", "continent_code" => "AF", "name_tr" => "Sierra Leone"],
            ["name" => "Singapore", "code" => "SG", "phone" => 65, "symbol" => "$", "capital" => "Singapur", "currency" => "SGD", "continent_code" => "AS", "name_tr" => "Singapur"],
            ["name" => "St Martin", "code" => "SX", "phone" => 721, "symbol" => "ƒ", "capital" => "Philipsburg", "currency" => "ANG", "continent_code" => "NA", "name_tr" => "St Martin"],
            ["name" => "Slovakia", "code" => "SK", "phone" => 421, "symbol" => "€", "capital" => "Bratislava", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Slovakya"],
            ["name" => "Slovenia", "code" => "SI", "phone" => 386, "symbol" => "€", "capital" => "Ljubljana", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "Slovenya"],
            ["name" => "Solomon Islands", "code" => "SB", "phone" => 677, "symbol" => "Si$", "capital" => "Honiara", "currency" => "SBD", "continent_code" => "OC", "name_tr" => "Solomon Adaları"],
            ["name" => "Somalia", "code" => "SO", "phone" => 252, "symbol" => "Sh.so.", "capital" => "Mogadishu", "currency" => "SOS", "continent_code" => "AF", "name_tr" => "Somali"],
            ["name" => "South Africa", "code" => "ZA", "phone" => 27, "symbol" => "R", "capital" => "Pretoria", "currency" => "ZAR", "continent_code" => "AF", "name_tr" => "Güney Afrika"],
            ["name" => "South Georgia and the South Sandwich Islands", "code" => "GS", "phone" => 500, "symbol" => "£", "capital" => "Grytviken", "currency" => "GBP", "continent_code" => "AN", "name_tr" => "Güney Georgia ve Güney Sandwich Adaları"],
            ["name" => "South Sudan", "code" => "SS", "phone" => 211, "symbol" => "£", "capital" => "Juba", "currency" => "SSP", "continent_code" => "AF", "name_tr" => "Güney Sudan"],
            ["name" => "Spain", "code" => "ES", "phone" => 34, "symbol" => "€", "capital" => "Madrid", "currency" => "EUR", "continent_code" => "EU", "name_tr" => "ispanya"],
            ["name" => "Sri Lanka", "code" => "LK", "phone" => 94, "symbol" => "Rs", "capital" => "Colombo", "currency" => "LKR", "continent_code" => "AS", "name_tr" => "Sri Lanka"],
            ["name" => "Sudan", "code" => "SD", "phone" => 249, "symbol" => ".س.ج", "capital" => "Khartoum", "currency" => "SDG", "continent_code" => "AF", "name_tr" => "Sudan"],
            ["name" => "Suriname", "code" => "SR", "phone" => 597, "symbol" => "$", "capital" => "Paramaribo", "currency" => "SRD", "continent_code" => "SA", "name_tr" => "Surinam"],
            ["name" => "Svalbard and Jan Mayen", "code" => "SJ", "phone" => 47, "symbol" => "kr", "capital" => "Longyearbyen", "currency" => "NOK", "continent_code" => "EU", "name_tr" => "Svalbard ve Jan Mayen"],
            ["name" => "Swaziland", "code" => "SZ", "phone" => 268, "symbol" => "E", "capital" => "Mbabane", "currency" => "SZL", "continent_code" => "AF", "name_tr" => "Svaziland"],
            ["name" => "Sweden", "code" => "SE", "phone" => 46, "symbol" => "kr", "capital" => "Stockholm", "currency" => "SEK", "continent_code" => "EU", "name_tr" => "İsveç"],
            ["name" => "Switzerland", "code" => "CH", "phone" => 41, "symbol" => "CHf", "capital" => "Berne", "currency" => "CHF", "continent_code" => "EU", "name_tr" => "İsviçre"],
            ["name" => "Syrian Arab Republic", "code" => "SY", "phone" => 963, "symbol" => "LS", "capital" => "Damascus", "currency" => "SYP", "continent_code" => "AS", "name_tr" => "Suriye Arap Cumhuriyeti"],
            ["name" => "Taiwan, Province of China", "code" => "TW", "phone" => 886, "symbol" => "$", "capital" => "Taipei", "currency" => "TWD", "continent_code" => "AS", "name_tr" => "Tayvan, Çin'in bölgesi"],
            ["name" => "Tajikistan", "code" => "TJ", "phone" => 992, "symbol" => "SM", "capital" => "Dushanbe", "currency" => "TJS", "continent_code" => "AS", "name_tr" => "Tacikistan"],
            ["name" => "Tanzania, United Republic of", "code" => "TZ", "phone" => 255, "symbol" => "TSh", "capital" => "Dodoma", "currency" => "TZS", "continent_code" => "AF", "name_tr" => "Tanzanya Birleşik Cumhuriyeti"],
            ["name" => "Thailand", "code" => "TH", "phone" => 66, "symbol" => "฿", "capital" => "Bangkok", "currency" => "THB", "continent_code" => "AS", "name_tr" => "Tayland"],
            ["name" => "Timor-Leste", "code" => "TL", "phone" => 670, "symbol" => "$", "capital" => "Dili", "currency" => "USD", "continent_code" => "AS", "name_tr" => "Doğu Timor"],
            ["name" => "Togo", "code" => "TG", "phone" => 228, "symbol" => "CFA", "capital" => "Lome", "currency" => "XOF", "continent_code" => "AF", "name_tr" => "Gitmek"],
            ["name" => "Tokelau", "code" => "TK", "phone" => 690, "symbol" => "$", "capital" => "", "currency" => "NZD", "continent_code" => "OC", "name_tr" => "Tokelau"],
            ["name" => "Tonga", "code" => "TO", "phone" => 676, "symbol" => "$", "capital" => "Nuku'alofa", "currency" => "TOP", "continent_code" => "OC", "name_tr" => "Tonga"],
            ["name" => "Trinidad and Tobago", "code" => "TT", "phone" => 1868, "symbol" => "$", "capital" => "Port of Spain", "currency" => "TTD", "continent_code" => "NA", "name_tr" => "Trinidad ve Tobago"],
            ["name" => "Tunisia", "code" => "TN", "phone" => 216, "symbol" => "ت.د", "capital" => "Tunis", "currency" => "TND", "continent_code" => "AF", "name_tr" => "Tunus"],
            ["name" => "Turkey", "code" => "TR", "phone" => 90, "symbol" => "₺", "capital" => "Ankara", "currency" => "TRY", "continent_code" => "AS", "name_tr" => "Türkiye"],
            ["name" => "Turkmenistan", "code" => "TM", "phone" => 7370, "symbol" => "T", "capital" => "Ashgabat", "currency" => "TMT", "continent_code" => "AS", "name_tr" => "Türkmenistan"],
            ["name" => "Turks and Caicos Islands", "code" => "TC", "phone" => 1649, "symbol" => "$", "capital" => "Cockburn Town", "currency" => "USD", "continent_code" => "NA", "name_tr" => "Turks ve Caicos Adaları"],
            ["name" => "Tuvalu", "code" => "TV", "phone" => 688, "symbol" => "$", "capital" => "Funafuti", "currency" => "AUD", "continent_code" => "OC", "name_tr" => "Tuvalu"],
            ["name" => "Uganda", "code" => "UG", "phone" => 256, "symbol" => "USh", "capital" => "Kampala", "currency" => "UGX", "continent_code" => "AF", "name_tr" => "Uganda"],
            ["name" => "Ukraine", "code" => "UA", "phone" => 380, "symbol" => "₴", "capital" => "Kiev", "currency" => "UAH", "continent_code" => "EU", "name_tr" => "Ukrayna"],
            ["name" => "United Arab Emirates", "code" => "AE", "phone" => 971, "symbol" => "إ.د", "capital" => "Abu Dhabi", "currency" => "AED", "continent_code" => "AS", "name_tr" => "Birleşik Arap Emirlikleri"],
            ["name" => "United Kingdom", "code" => "GB", "phone" => 44, "symbol" => "£", "capital" => "London", "currency" => "GBP", "continent_code" => "EU", "name_tr" => "Birleşik Krallık"],
            ["name" => "United States", "code" => "US", "phone" => 1, "symbol" => "$", "capital" => "Washington", "currency" => "USD", "continent_code" => "NA", "name_tr" => "Amerika Birleşik Devletleri"],
            ["name" => "United States Minor Outlying Islands", "code" => "UM", "phone" => 1, "symbol" => "$", "capital" => "", "currency" => "USD", "continent_code" => "NA", "name_tr" => "Amerika Birleşik Devletleri Küçük Dış Adaları"],
            ["name" => "Uruguay", "code" => "UY", "phone" => 598, "symbol" => "$", "capital" => "Montevideo", "currency" => "UYU", "continent_code" => "SA", "name_tr" => "Uruguay"],
            ["name" => "Uzbekistan", "code" => "UZ", "phone" => 998, "symbol" => "лв", "capital" => "Tashkent", "currency" => "UZS", "continent_code" => "AS", "name_tr" => "Özbekistan"],
            ["name" => "Vanuatu", "code" => "VU", "phone" => 678, "symbol" => "VT", "capital" => "Port Vila", "currency" => "VUV", "continent_code" => "OC", "name_tr" => "Vanuatu"],
            ["name" => "Venezuela", "code" => "VE", "phone" => 58, "symbol" => "Bs", "capital" => "Caracas", "currency" => "VEF", "continent_code" => "SA", "name_tr" => "Venezuela"],
            ["name" => "Viet Nam", "code" => "VN", "phone" => 84, "symbol" => "₫", "capital" => "Hanoi", "currency" => "VND", "continent_code" => "AS", "name_tr" => "Vietnam"],
            ["name" => "Virgin Islands, British", "code" => "VG", "phone" => 1284, "symbol" => "$", "capital" => "Road Town", "currency" => "USD", "continent_code" => "NA", "name_tr" => "Virgin Adaları, İngiliz"],
            ["name" => "Virgin Islands, U.s.", "code" => "VI", "phone" => 1340, "symbol" => "$", "capital" => "Charlotte Amalie", "currency" => "USD", "continent_code" => "NA", "name_tr" => "Virgin Adaları, U.s."],
            ["name" => "Wallis and Futuna", "code" => "WF", "phone" => 681, "symbol" => "₣", "capital" => "Mata Utu", "currency" => "XPF", "continent_code" => "OC", "name_tr" => "Wallis ve Futuna"],
            ["name" => "Western Sahara", "code" => "EH", "phone" => 212, "symbol" => "MAD", "capital" => "El-Aaiun", "currency" => "MAD", "continent_code" => "AF", "name_tr" => "Batı Sahra"],
            ["name" => "Yemen", "code" => "YE", "phone" => 967, "symbol" => "﷼", "capital" => "Sanaa", "currency" => "YER", "continent_code" => "AS", "name_tr" => "Yemen"],
            ["name" => "Zambia", "code" => "ZM", "phone" => 260, "symbol" => "ZK", "capital" => "Lusaka", "currency" => "ZMW", "continent_code" => "AF", "name_tr" => "Zambiya"],
            ["name" => "Zimbabwe", "code" => "ZW", "phone" => 263, "symbol" => "$", "capital" => "Harare", "currency" => "ZWL", "continent_code" => "AF", "name_tr" => "Zimbabve"]
        ];
        DB::table('countries')->insert($datas);

    }
}
