<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $datas = array(
            array("name" => "Afrikaans", "code" => "af", "native" => "Afrikaans"),
            array("name" => "Albanian - shqip", "code" => "sq", "native" => "shqip"),
            array("name" => "Amharic - አማርኛ", "code" => "am", "native" => "አማርኛ"),
            array("name" => "Arabic - العربية", "code" => "ar", "native" => "العربية"),
            array("name" => "Aragonese - aragonés", "code" => "an", "native" => "aragonés"),
            array("name" => "Armenian - հայերեն", "code" => "hy", "native" => "հայերեն"),
            array("name" => "Asturian - asturianu", "code" => "ast", "native" => "asturianu"),
            array("name" => "Azerbaijani - azərbaycan dili", "code" => "az", "native" => "azərbaycan dili"),
            array("name" => "Basque - euskara", "code" => "eu", "native" => "euskara"),
            array("name" => "Belarusian - беларуская", "code" => "be", "native" => "беларуская"),
            array("name" => "Bengali - বাংলা", "code" => "bn", "native" => "বাংলা"),
            array("name" => "Bosnian - bosanski", "code" => "bs", "native" => "bosanski"),
            array("name" => "Breton - brezhoneg", "code" => "br", "native" => "brezhoneg"),
            array("name" => "Bulgarian - български", "code" => "bg", "native" => "български"),
            array("name" => "Catalan - català", "code" => "ca", "native" => "català"),
            array("name" => "Central Kurdish - کوردی (دەستنوسی عەرەبی)", "code" => "ckb", "native" => "کوردی (دەستنوسی عەرەبی)"),
            array("name" => "Chinese - 中文", "code" => "zh", "native" => "中文"),
            array("name" => "Chinese (Hong Kong) - 中文（香港）", "code" => "zh-HK", "native" => "中文（香港）"),
            array("name" => "Chinese (Simplified) - 中文（简体）", "code" => "zh-CN", "native" => "中文（简体）"),
            array("name" => "Chinese (Traditional) - 中文（繁體）", "code" => "zh-TW", "native" => "中文（繁體）"),
            array("name" => "Corsican", "code" => "co", "native" => "Corsican"),
            array("name" => "Croatian - hrvatski", "code" => "hr", "native" => "hrvatski"),
            array("name" => "Czech - čeština", "code" => "cs", "native" => "čeština"),
            array("name" => "Danish - dansk", "code" => "da", "native" => "dansk"),
            array("name" => "Dutch - Nederlands", "code" => "nl", "native" => "Nederlands"),
            array("name" => "English", "code" => "en", "native" => "English"),
            array("name" => "English (Australia)", "code" => "en-AU", "native" => "English (Australia)"),
            array("name" => "English (Canada)", "code" => "en-CA", "native" => "English (Canada)"),
            array("name" => "English (India)", "code" => "en-IN", "native" => "English (India)"),
            array("name" => "English (New Zealand)", "code" => "en-NZ", "native" => "English (New Zealand)"),
            array("name" => "English (South Africa)", "code" => "en-ZA", "native" => "English (South Africa)"),
            array("name" => "English (United Kingdom)", "code" => "en-GB", "native" => "English (United Kingdom)"),
            array("name" => "English (United States)", "code" => "en-US", "native" => "English (United States)"),
            array("name" => "Esperanto - esperanto", "code" => "eo", "native" => "esperanto"),
            array("name" => "Estonian - eesti", "code" => "et", "native" => "eesti"),
            array("name" => "Faroese - føroyskt", "code" => "fo", "native" => "føroyskt"),
            array("name" => "Filipino", "code" => "fil", "native" => "Filipino"),
            array("name" => "Finnish - suomi", "code" => "fi", "native" => "suomi"),
            array("name" => "French - français", "code" => "fr", "native" => "français"),
            array("name" => "French (Canada) - français (Canada)", "code" => "fr-CA", "native" => "français (Canada)"),
            array("name" => "French (France) - français (France)", "code" => "fr-FR", "native" => "français (France)"),
            array("name" => "French (Switzerland) - français (Suisse)", "code" => "fr-CH", "native" => "français (Suisse)"),
            array("name" => "Galician - galego", "code" => "gl", "native" => "galego"),
            array("name" => "Georgian - ქართული", "code" => "ka", "native" => "ქართული"),
            array("name" => "German - Deutsch", "code" => "de", "native" => "Deutsch"),
            array("name" => "German (Austria) - Deutsch (Österreich)", "code" => "de-AT", "native" => "Deutsch (Österreich)"),
            array("name" => "German (Germany) - Deutsch (Deutschland)", "code" => "de-DE", "native" => "Deutsch (Deutschland)"),
            array("name" => "German (Liechtenstein) - Deutsch (Liechtenstein)", "code" => "de-LI", "native" => "Deutsch (Liechtenstein)"),
            array("name" => "German (Switzerland) - Deutsch (Schweiz)", "code" => "de-CH", "native" => "Deutsch (Schweiz)"),
            array("name" => "Greek - Ελληνικά", "code" => "el", "native" => "Ελληνικά"),
            array("name" => "Guarani", "code" => "gn", "native" => "Guarani"),
            array("name" => "Gujarati - ગુજરાતી", "code" => "gu", "native" => "ગુજરાતી"),
            array("name" => "Hausa", "code" => "ha", "native" => "Hausa"),
            array("name" => "Hawaiian - ʻŌlelo Hawaiʻi", "code" => "haw", "native" => "ʻŌlelo Hawaiʻi"),
            array("name" => "Hebrew - עברית", "code" => "he", "native" => "עברית"),
            array("name" => "Hindi - हिन्दी", "code" => "hi", "native" => "हिन्दी"),
            array("name" => "Hungarian - magyar", "code" => "hu", "native" => "magyar"),
            array("name" => "Icelandic - íslenska", "code" => "is", "native" => "íslenska"),
            array("name" => "Indonesian - Indonesia", "code" => "id", "native" => "Indonesia"),
            array("name" => "Interlingua", "code" => "ia", "native" => "Interlingua"),
            array("name" => "Irish - Gaeilge", "code" => "ga", "native" => "Gaeilge"),
            array("name" => "Italian - italiano", "code" => "it", "native" => "italiano"),
            array("name" => "Italian (Italy) - italiano (Italia)", "code" => "it-IT", "native" => "italiano (Italia)"),
            array("name" => "Italian (Switzerland) - italiano (Svizzera)", "code" => "it-CH", "native" => "italiano (Svizzera)"),
            array("name" => "Japanese - 日本語", "code" => "ja", "native" => "日本語"),
            array("name" => "Kannada - ಕನ್ನಡ", "code" => "kn", "native" => "ಕನ್ನಡ"),
            array("name" => "Kazakh - қазақ тілі", "code" => "kk", "native" => "қазақ тілі"),
            array("name" => "Khmer - ខ្មែរ", "code" => "km", "native" => "ខ្មែរ"),
            array("name" => "Korean - 한국어", "code" => "ko", "native" => "한국어"),
            array("name" => "Kurdish - Kurdî", "code" => "ku", "native" => "Kurdî"),
            array("name" => "Kyrgyz - кыргызча", "code" => "ky", "native" => "кыргызча"),
            array("name" => "Lao - ລາວ", "code" => "lo", "native" => "ລາວ"),
            array("name" => "Latin", "code" => "la", "native" => "Latin"),
            array("name" => "Latvian - latviešu", "code" => "lv", "native" => "latviešu"),
            array("name" => "Lingala - lingála", "code" => "ln", "native" => "lingála"),
            array("name" => "Lithuanian - lietuvių", "code" => "lt", "native" => "lietuvių"),
            array("name" => "Macedonian - македонски", "code" => "mk", "native" => "македонски"),
            array("name" => "Malay - Bahasa Melayu", "code" => "ms", "native" => "Bahasa Melayu"),
            array("name" => "Malayalam - മലയാളം", "code" => "ml", "native" => "മലയാളം"),
            array("name" => "Maltese - Malti", "code" => "mt", "native" => "Malti"),
            array("name" => "Marathi - मराठी", "code" => "mr", "native" => "मराठी"),
            array("name" => "Mongolian - монгол", "code" => "mn", "native" => "монгол"),
            array("name" => "Nepali - नेपाली", "code" => "ne", "native" => "नेपाली"),
            array("name" => "Norwegian - norsk", "code" => "no", "native" => "norsk"),
            array("name" => "Norwegian Bokmål - norsk bokmål", "code" => "nb", "native" => "norsk bokmål"),
            array("name" => "Norwegian Nynorsk - nynorsk", "code" => "nn", "native" => "nynorsk"),
            array("name" => "Occitan", "code" => "oc", "native" => "Occitan"),
            array("name" => "Oriya - ଓଡ଼ିଆ", "code" => "or", "native" => "ଓଡ଼ିଆ"),
            array("name" => "Oromo - Oromoo", "code" => "om", "native" => "Oromoo"),
            array("name" => "Pashto - پښتو", "code" => "ps", "native" => "پښتو"),
            array("name" => "Persian - فارسی", "code" => "fa", "native" => "فارسی"),
            array("name" => "Polish - polski", "code" => "pl", "native" => "polski"),
            array("name" => "Portuguese - português", "code" => "pt", "native" => "português"),
            array("name" => "Portuguese (Brazil) - português (Brasil)", "code" => "pt-BR", "native" => "português (Brasil)"),
            array("name" => "Portuguese (Portugal) - português (Portugal)", "code" => "pt-PT", "native" => "português (Portugal)"),
            array("name" => "Punjabi - ਪੰਜਾਬੀ", "code" => "pa", "native" => "ਪੰਜਾਬੀ"),
            array("name" => "Quechua", "code" => "qu", "native" => "Quechua"),
            array("name" => "Romanian - română", "code" => "ro", "native" => "română"),
            array("name" => "Romanian (Moldova) - română (Moldova)", "code" => "mo", "native" => "română (Moldova)"),
            array("name" => "Romansh - rumantsch", "code" => "rm", "native" => "rumantsch"),
            array("name" => "Russian - русский", "code" => "ru", "native" => "русский"),
            array("name" => "Scottish Gaelic", "code" => "gd", "native" => "Scottish Gaelic"),
            array("name" => "Serbian - српски", "code" => "sr", "native" => "српски"),
            array("name" => "Serbo - Croatian", "code" => "sh", "native" => "Croatian"),
            array("name" => "Shona - chiShona", "code" => "sn", "native" => "chiShona"),
            array("name" => "Sindhi", "code" => "sd", "native" => "Sindhi"),
            array("name" => "Sinhala - සිංහල", "code" => "si", "native" => "සිංහල"),
            array("name" => "Slovak - slovenčina", "code" => "sk", "native" => "slovenčina"),
            array("name" => "Slovenian - slovenščina", "code" => "sl", "native" => "slovenščina"),
            array("name" => "Somali - Soomaali", "code" => "so", "native" => "Soomaali"),
            array("name" => "Southern Sotho", "code" => "st", "native" => "Southern Sotho"),
            array("name" => "Spanish - español", "code" => "es", "native" => "español"),
            array("name" => "Spanish (Argentina) - español (Argentina)", "code" => "es-AR", "native" => "español (Argentina)"),
            array("name" => "Spanish (Latin America) - español (Latinoamérica)", "code" => "es-419", "native" => "español (Latinoamérica)"),
            array("name" => "Spanish (Mexico) - español (México)", "code" => "es-MX", "native" => "español (México)"),
            array("name" => "Spanish (Spain) - español (España)", "code" => "es-ES", "native" => "español (España)"),
            array("name" => "Spanish (United States) - español (Estados Unidos)", "code" => "es-US", "native" => "español (Estados Unidos)"),
            array("name" => "Sundanese", "code" => "su", "native" => "Sundanese"),
            array("name" => "Swahili - Kiswahili", "code" => "sw", "native" => "Kiswahili"),
            array("name" => "Swedish - svenska", "code" => "sv", "native" => "svenska"),
            array("name" => "Tajik - тоҷикӣ", "code" => "tg", "native" => "тоҷикӣ"),
            array("name" => "Tamil - தமிழ்", "code" => "ta", "native" => "தமிழ்"),
            array("name" => "Tatar", "code" => "tt", "native" => "Tatar"),
            array("name" => "Telugu - తెలుగు", "code" => "te", "native" => "తెలుగు"),
            array("name" => "Thai - ไทย", "code" => "th", "native" => "ไทย"),
            array("name" => "Tigrinya - ትግርኛ", "code" => "ti", "native" => "ትግርኛ"),
            array("name" => "Tongan - lea fakatonga", "code" => "to", "native" => "lea fakatonga"),
            array("name" => "Turkish - Türkçe", "code" => "tr", "native" => "Türkçe"),
            array("name" => "Turkmen", "code" => "tk", "native" => "Turkmen"),
            array("name" => "Twi", "code" => "tw", "native" => "Twi"),
            array("name" => "Ukrainian - українська", "code" => "uk", "native" => "українська"),
            array("name" => "Urdu - اردو", "code" => "ur", "native" => "اردو"),
            array("name" => "Uyghur", "code" => "ug", "native" => "Uyghur"),
            array("name" => "Uzbek - o‘zbek", "code" => "uz", "native" => "o‘zbek"),
            array("name" => "Vietnamese - Tiếng Việt", "code" => "vi", "native" => "Tiếng Việt"),
            array("name" => "Walloon - wa", "code" => "wa", "native" => "wa"),
            array("name" => "Welsh - Cymraeg", "code" => "cy", "native" => "Cymraeg"),
            array("name" => "Western Frisian", "code" => "fy", "native" => "Western Frisian"),
            array("name" => "Xhosa", "code" => "xh", "native" => "Xhosa"),
            array("name" => "Yiddish", "code" => "yi", "native" => "Yiddish"),
            array("name" => "Yoruba - Èdè Yorùbá", "code" => "yo", "native" => "Èdè Yorùbá"),
            array("name" => "Zulu - isiZulu", "code" => "zu", "native" => "isiZulu")
        );
        DB::table('languages')->insert($datas);
    }
}
